steps:
# Build and push Docker image for the account service
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/ordering-system-404411/accountmicroservice:latest'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/ordering-system-404411/accountmicroservice:latest'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'K8S/account-database/account-mariadb-gke-pvc.yaml'

  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ordering-system'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'K8S/account-database/mariadb-account-depl.yaml'

  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ordering-system'

# Apply Kubernetes manifests for the account service
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'K8S/account-service/account-depl.yaml'

  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ordering-system'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
      - 'rollout'
      - 'restart'
      - 'deployment'
      - 'account-depl'
      - '-n' 
      - 'ordering-system'

  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ordering-system'

images: ['gcr.io/ordering-system-404411/accountmicroservice:latest']
logsBucket: "gs://accountci-logs-bucket"


