steps:
# Build and push Docker image for the account service
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/your-project-id/accountmicroservice:$COMMIT_SHA'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/your-project-id/accountmicroservice:$COMMIT_SHA'

# Apply Kubernetes manifests for the account database
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s/account-database/mariadb-secret.yaml'

  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west4'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ordering-system-autopilot-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s/account-database/mariadb-pvc.yaml'

  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west4'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ordering-system-autopilot-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s/account-database/'

  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west4'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ordering-system-autopilot-cluster'

# Apply Kubernetes manifests for the account service
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s/account-service/'

  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west4'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ordering-system-autopilot-cluster'

images: ['gcr.io/your-project-id/accountmicroservice']
