apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-account-claim
  namespace: ordering-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
