apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-depl
  namespace: ordering-system
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
        kubernetes.io/arch: arm64

      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb
      volumes:
      - name: mariadb
        persistentVolumeClaim:
          claimName: mariadb-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-clusterip-srv
  namespace: ordering-system
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
  - name: mariadb
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-loadbalancer
  namespace: ordering-system
spec:
  type: LoadBalancer
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
