apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-account
  template:
    metadata:
      labels:
        app: mariadb-account
    spec:
      containers:
        - name: mariadb-account
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mariadb-account-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-account-storage
          persistentVolumeClaim:
            claimName: mariadb-account-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-account-service
spec:
  selector:
    app: mariadb-account
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
