apiVersion: v1
kind: Service
metadata:
  name: mariadb-account
  namespace: ordering-system
spec:
  clusterIP: None  # This makes the service headless
  selector:
    app: mariadb-account
  ports:
  - protocol: TCP
    port: 3306
