apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-depl
  namespace: ordering-system 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountmicroservice
  template:
    metadata:
      labels:
        app: accountmicroservice
    spec:
      containers:
        - name: accountmicroservice
          image: gcr.io/ordering-system-404411/accountmicroservice:HERE
          imagePullPolicy: Always
          env:
            - name: COMMIT_SHA
              valueFrom:
                configMapKeyRef:
                  name: commit-sha-config  # Name of the ConfigMap
                  key: COMMIT_SHA   
---
apiVersion: v1
kind: Service
metadata:
  name: account-clusterip-srv
  namespace: ordering-system
spec:
  type: ClusterIP
  selector:
    app: accountmicroservice
  ports:
    - name: accountmicroservice 
      protocol: TCP
      port: 80
      targetPort: 80
