apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-depl
  namespace: ordering-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountmicroservice
  template:
    metadata:
      labels:
        app: accountmicroservice
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
        kubernetes.io/arch: arm64
      containers:
        - name: accountmicroservice
          image: gcr.io/ordering-system-404411/accountmicroservice:$COMMIT_SHA
          resources:
            requests:
              memory: "64Mi"  
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: account-clusterip-srv
  namespace: ordering-system
spec:
  type: ClusterIP
  selector:
    app: accountmicroservice
  ports:
    - name: accountmicroservice
      protocol: TCP
      port: 80
      targetPort: 80
