apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-depl
  namespace: ordering-system 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: accountmicroservice
  template:
    metadata:
      labels:
        app: accountmicroservice
    spec:
      containers:
        - name: accountmicroservice
          image: orderingsystemcontainerregistry.azurecr.io/accountmicroservice:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: account-clusterip-srv
  namespace: ordering-system
spec:
  type: ClusterIP
  selector:
    app: accountmicroservice
  ports:
    - name: accountmicroservice 
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: account-depl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account-depl
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
