name: Build Multi-Platform Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-platform image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t your-image-name .
          docker push your-image-name
        env:
          DOCKER_CLI_ARCH: amd64
