name: Deploy to Local Kubernetes

on:
  push:
    branches:
      - localdev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}/accountmicroservice" .

      - name: Push Docker Image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/accountmicroservice"

      - name: Set up Kubernetes
        uses: azure/setup-k8s@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Use Docker Desktop Kubernetes Context
        run: |
          kubectl config use-context docker-desktop 
          kubectl get pods

      - name: Deploy Database Secret to Kubernetes 
        run: |
          kubectl apply -f K8S/account-mariadb/mariadb-account-secret.yaml

      - name: Deploy Database Persistent Volume to Kubernetes
        run: |
          kubectl apply -f K8S/account-mariadb/mariadb-account-claim.yaml
 
      - name: Deploy Database to Kubernetes
        run: |
          kubectl apply -f K8S/account-mariadb/mariadb-account-depl.yaml

      - name: Deploy Application to Kubernetes
        run: | 
          kubectl apply -f K8S/account-depl.yaml
