name: Build Multi-Platform Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build multi-platform image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t orderingsystemcontainerregistry.azurecr.io/accountmicroservice .
        env:
          DOCKER_CLI_ARCH: amd64
          
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: orderingsystemcontainerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push image to Azure Container Registry
        run: |
          docker push orderingsystemcontainerregistry.azurecr.io/accountmicroservice:latest
